### ISSUE TITLE
Enable LGTM analysis 

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/theme-tool#7]

**Comment by bhajneet** [comment]
Done

**Comment by saihaj** [comment]
Still not working because we should have LGTM results in PR #21 . If we can get #10 for CI then I don’t need this. Rest is up to you @Harjot1Singh
